[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "game_utils2"
version = "0.2.0"
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.20",
]

[tool.setuptools.packages.find]
where = ["src"]
